---
- name: Update data group.
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  
   - name: Sleep for 60 seconds and continue with play
     wait_for:
       timeout: 60
     delegate_to: localhost

   - debug:
       msg: "My name is {{name}} and I'm a {{title}}."
     failed_when: "'failure' in title"
